parameters:
    dwd_qiniu_sdk.util.class: DWD\QiniuSdkBundle\Util\Qiniu

services:
   dwd_qiniu_sdk:
      class: %dwd_qiniu_sdk.util.class%
      arguments: 
         - @service_container
         - %qiniu_sdk_accessKey%
         - %qiniu_sdk_secretKey%
         - %qiniu_sdk_bucket%
         - %qiniu_sdk_domain%
